export const airtableSchema = {
  operations: {
    tables: {
      clients: "Clients",
      clientProfiles: "Client Profiles",
      clientLessonSummaries: "Client Lesson Summaries",
      lessons: "Lessons",
      clientExternals: "Client Externals",
      providerAccounts: "Provider Accounts",
      cardExternals: "Card Externals",
      orders: "Orders",
      orderItems: "Order Items",
      promotions: "Promotions",
      promotionRedemptions: "Promotion Redemptions",
      orderExternals: "Order Externals",
      refunds: "Refunds",
      refundItems: "Refund Items",
      refundExternals: "Refund Externals",
      externalActions: "External Actions",
      invoices: "Invoices",
      invoiceExternals: "Invoice Externals",
      creditAccounts: "Credit Accounts",
      creditReservations: "Credit Reservations",
      creditLedgerEntries: "Credit Ledger Entries",
      organizationIntegrations: "Organization Integrations",
      webhookEvents: "Webhook Events",
      webhookDeliveries: "Webhook Deliveries",
      appConfig: "App Config",
    },
    fields: {
      clientProfiles: {
        clientLink: "Client",
        lessonSummaryLink: "Client Lesson Summary",
        status: "Status",
        notes: "Notes",
        client: "Client",
        organization: "Organization",
        lessons: "Lessons",
        orders: "Orders",
        creditAccount: "Credit Account",
        clientActivationSummary: "Client Activation Summary",
        studentProfiles: "Student Profiles",
        clientName: "Client Name",
        clientPhone: "Client Phone",
        lessonCount: "Lesson Count",
        orderCount: "Order Count",
        hasCreditAccount: "Has Credit Account",
        hasClientActivationSummary: "Has Client Activation Summary",
        hasActivity: "Has Activity",
        needsActivationSummaryCreation: "Needs Activation Summary Creation",
        missingClient: "Missing Client",
        missingOrganization: "Missing Organization",
        missingCreditAccount: "Missing Credit Account",
        missingActivationSummary: "Missing Activation Summary",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      clientLessonSummaries: {
        profileLink: "Client Profile",
        lastLessonAt: "Last Lesson At",
        nextLessonAt: "Next Lesson At",
        completedLessonCount: "Completed Lesson Count",
        canceledLessonCount: "Canceled Lesson Count",
        noShowLessonCount: "No Show Lesson Count",
        scheduledFutureLessonCount: "Scheduled Future Lesson Count",
        lastLessonStatus: "Last Lesson Status",
        lastRefreshedAt: "Last Refreshed At",
        needsRefresh: "Sync Requested",
        syncStatus: "Sync Status",
        syncError: "Sync Error",
      },
      lessons: {
        // Core
        status: "Status",
        startAt: "Start At",
        cancellationReason: "Cancellation Reason",
        canceledAt: "Canceled At",
        completedAt: "Completed At",
        resolutionStatus: "Resolution Status",
        outcomeNotes: "Outcome Notes",
        notes: "Notes",
        coachConfirmed: "Coach Confirmed",
        requestScheduling: "Request Scheduling",
        // Links
        clientProfile: "Client Profile",
        lessonType: "Lesson Type",
        lessonSiteConfig: "Lesson Site Config",
        coachProfile: "Coach Profile",
        payingCreditAccount: "Paying Credit Account",
        creditReservations: "Credit Reservations",
        creditLedgerEntry: "Credit Ledger Entry",
        // Lookups
        organization: "Organization",
        client: "Client",
        expectedLessonCreditCost: "Expected Lesson Credit Cost",
        reservationIsActive: "Reservation Is Active",
        reservationHasLockDebit: "Reservation Has Lock Debit",
        reservationStatus: "Reservation Status",
        // Rollups
        lessonDebitCount: "Lesson Debit Count",
        lessonDebitTotal: "Lesson Debit Total",
        // Helpers
        futureStartAt: "Future Start At",
        hasPayingCreditAccount: "Has Paying Credit Account",
        hasActiveReservation: "Has Active Reservation",
        hasLessonDebit: "Has Lesson Debit",
        expectedDebitCredits: "Expected Debit Credits",
        hasLockDebitViaReservation: "Has Lock Debit Via Reservation",
        isTerminalLesson: "Is Terminal Lesson",
        hasNoCriticalErrors: "Has No Critical Errors",
        hasCreditLedgerImpactingException: "Has Credit Ledger Impacting Exception",
        reservationReady: "Reservation Ready",
        scheduledStateValid: "Scheduled State Valid",
        // Checks
        missingRequiredLinks: "Missing Required Links",
        hasException: "Has Exception",
      },
      orders: {
        status: "Status",
        billingState: "Billing State",
        paymentCollectionMethod: "Payment Collection Method",
        cardReadiness: "Card Readiness",
        cardReadinessError: "Card Readiness Error",
        invoiceReadiness: "Invoice Readiness",
        invoiceReadinessError: "Invoice Readiness Error",
        orderedAt: "Ordered At",
        amountPaid: "Amount Paid",
        paidAt: "Paid At",
        currency: "Currency",
        notes: "Notes",
        openingRequested: "Opening Requested",
        promotionResolutionRequested: "Promotion Resolution Requested",
        organization: "Organization",
        clientProfile: "Client Profile",
        orderItems: "Order Items",
        orderExternal: "Order External",
        orderExternals: "Order Externals",
        client: "Client",
        clientProfileOrganization: "Client Profile Organization",
        orderItemsCount: "Order Items Count",
        orderItemsSubtotal: "Order Items Subtotal",
        orderItemsDiscount: "Order Items Discount",
        orderItemsTax: "Order Items Tax",
        orderItemsServiceCharge: "Order Items Service Charge",
        orderItemsContribution: "Order Items Contribution",
        orderItemsCreditGrantedTotal: "Order Items Credit Granted Total",
        orderItemsSnapshotCompletedCount: "Order Items Snapshot Completed Count",
        orderItemsExceptionCount: "Order Items Exception Count",
        orderItemsDraftPromotionRedemptionCount: "Order Items Draft Promotion Redemption Count",
        orderItemsRefundCount: "Order Items Refund Count",
        orderItemsRefundAmount: "Order Items Refund Amount",
        orderItemsCompletedRefundCount: "Order Items Completed Refund Count",
        orderItemsCompletedRefundAmount: "Order Items Completed Refund Amount",
        subtotal: "Subtotal",
        discount: "Discount",
        tax: "Tax",
        serviceCharge: "Service Charge",
        total: "Total",
        balanceDue: "Balance Due",
        hasUnresolvedPromotionRedemptions: "Has Unresolved Promotion Redemptions",
        readyToOpen: "Ready To Open",
        openBlockReason: "Open Block Reason",
        openStateValid: "Open State Valid",
        isOrderReady: "Is Order Ready",
        readyForProviderAction: "Ready For Provider Action",
        collectionBlockReason: "Collection Block Reason",
        openingRequestedInvalid: "Opening Requested Invalid",
        missingRequiredLinks: "Missing Required Links",
        clientProfileOrgMismatch: "Client Profile Org Mismatch",
        orderItemsMissing: "Order Items Missing",
        orderItemsSnapshotIncomplete: "Order Items Snapshot Incomplete",
        orderItemsHaveExceptions: "Order Items Have Exceptions",
        paymentCollectionMethodMissingWhenOpen: "Payment Collection Method Missing When Open",
        amountPaidExceedsTotal: "Amount Paid Exceeds Total",
        paidStatusInvalid: "Paid Status Invalid",
        openStatusInvalid: "Open Status Invalid",
        refundedStatusInvalid: "Refunded Status Invalid",
        partiallyRefundedStatusInvalid: "Partially Refunded Status Invalid",
        billingStateInvalid: "Billing State Invalid",
        collectionPathLogicInvalid: "Collection Path Logic Invalid",
        hasStructureProblem: "Has Structure Problem",
        structureProblem: "Structure Problem",
        hasSetupProblem: "Has Setup Problem",
        setupProblem: "Setup Problem",
        hasAmountProblem: "Has Amount Problem",
        amountProblem: "Amount Problem",
        hasStatusProblem: "Has Status Problem",
        statusProblem: "Status Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasChildProblem: "Has Child Problem",
        childProblem: "Child Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        createdAt: "Created At",
        modifiedAt: "Modified At",
        canceledAt: "Canceled At",
      },
      orderItems: {
        status: "Status",
        quantity: "Quantity",
        notes: "Notes",
        offeringNameSnapshot: "Offering Name Snapshot",
        unitPriceSnapshot: "Unit Price Snapshot",
        creditsGrantedPerUnitSnapshot: "Credits Granted Per Unit Snapshot",
        taxRateSnapshot: "Tax Rate Snapshot",
        serviceChargeRateSnapshot: "Service Charge Rate Snapshot",
        order: "Order",
        offering: "Offering",
        promotionRedemptions: "Promotion Redemptions",
        refundItems: "Refund Items",
        creditLedgerEntries: "Credit Ledger Entries",
        organization: "Organization",
        clientProfile: "Client Profile",
        orderStatus: "Order Status",
        offeringOrganization: "Offering Organization",
        offeringStatus: "Offering Status",
        offeringHasException: "Offering Has Exception",
        offeringName: "Offering Name",
        basePrice: "Base Price",
        creditsGranted: "Credits Granted",
        offeringTaxRate: "Offering Tax Rate",
        offeringServiceChargeRate: "Offering Service Charge Rate",
        promotionRedemptionCount: "Promotion Redemption Count",
        draftPromotionRedemptionCount: "Draft Promotion Redemption Count",
        appliedPromotionRedemptionCount: "Applied Promotion Redemption Count",
        removedPromotionRedemptionCount: "Removed Promotion Redemption Count",
        activePromotionRedemptionCount: "Active Promotion Redemption Count",
        appliedPromotionDiscountTotal: "Applied Promotion Discount Total",
        promotionRedemptionExceptionCount: "Promotion Redemption Exception Count",
        promotionSnapshotAnchorCount: "Promotion Snapshot Anchor Count",
        refundItemCount: "Refund Item Count",
        completedRefundItemCount: "Completed Refund Item Count",
        refundAmountTotal: "Refund Amount Total",
        completedRefundAmountTotal: "Completed Refund Amount Total",
        draftEditable: "Draft Editable",
        snapshotComplete: "Snapshot Complete",
        snapshotCompleteHelper: "Snapshot Complete Helper",
        lineSubtotal: "Line Subtotal",
        lineDiscount: "Line Discount",
        taxableBase: "Taxable Base",
        lineTax: "Line Tax",
        lineServiceCharge: "Line Service Charge",
        lineTotalContribution: "Line Total Contribution",
        creditsGrantedTotal: "Credits Granted Total",
        unresolvedDraftPromotionRedemptions: "Unresolved Draft Promotion Redemptions",
        offeringProblem: "Offering Problem",
        offeringProblemImpactsOrderItem: "Offering Problem Impacts Order Item",
        offeringDriftDetected: "Offering Drift Detected",
        offeringSnapshotRefreshAllowed: "Offering Snapshot Refresh Allowed",
        needsSnapshotRefresh: "Needs Snapshot Refresh",
        snapshotRefreshBlocked: "Snapshot Refresh Blocked",
        snapshotRefreshBlockReason: "Snapshot Refresh Block Reason",
        readyToActivate: "Ready To Activate",
        activateBlockReason: "Activate Block Reason",
        activeStateValid: "Active State Valid",
        canceledStateInvalid: "Canceled State Invalid",
        refundedStateInvalid: "Refunded State Invalid",
        missingRequiredLinks: "Missing Required Links",
        offeringMissingWhileDraftEditable: "Offering Missing While Draft Editable",
        offeringOrgMismatch: "Offering Org Mismatch",
        offeringNotActive: "Offering Not Active",
        offeringNameSnapshotMissing: "Offering Name Snapshot Missing",
        unitPriceSnapshotInvalid: "Unit Price Snapshot Invalid",
        creditsGrantedPerUnitSnapshotInvalid: "Credits Granted Per Unit Snapshot Invalid",
        quantityInvalid: "Quantity Invalid",
        lineDiscountInvalid: "Line Discount Invalid",
        lineTaxInvalid: "Line Tax Invalid",
        lineServiceChargeInvalid: "Line Service Charge Invalid",
        promotionRedemptionImpactingExceptionPresent: "Promotion Redemption Impacting Exception Present",
        hasStructureProblem: "Has Structure Problem",
        structureProblem: "Structure Problem",
        hasDependencyProblem: "Has Dependency Problem",
        dependencyProblem: "Dependency Problem",
        hasSnapshotProblem: "Has Snapshot Problem",
        snapshotProblem: "Snapshot Problem",
        hasAmountProblem: "Has Amount Problem",
        amountProblem: "Amount Problem",
        hasChildProblem: "Has Child Problem",
        childProblem: "Child Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        createdAt: "Created At",
        modifiedAt: "Modified At",
        activatedAt: "Activated At",
        canceledAt: "Canceled At",
      },
      promotionRedemptions: {
        status: "Status",
        applicationRequested: "Application Requested",
        notes: "Notes",
        promotionNameSnapshot: "Promotion Name Snapshot",
        discountTypeSnapshot: "Discount Type Snapshot",
        discountAmountSnapshot: "Discount Amount Snapshot",
        discountPercentSnapshot: "Discount Percent Snapshot",
        orderItem: "Order Item",
        promotion: "Promotion",
        order: "Order",
        organization: "Organization",
        clientProfile: "Client Profile",
        orderStatus: "Order Status",
        orderItemSubtotal: "Order Item Subtotal",
        orderItemOffering: "Order Item Offering",
        promotionOrganization: "Promotion Organization",
        promotionStatus: "Promotion Status",
        promotionHasException: "Promotion Has Exception",
        promotionName: "Promotion Name",
        discountType: "Discount Type",
        discountAmount: "Discount Amount",
        discountPercent: "Discount Percent",
        hasPromotion: "Has Promotion",
        draftEditable: "Draft Editable",
        draftRedemptionCountHelper: "Draft Redemption Count Helper",
        appliedRedemptionCountHelper: "Applied Redemption Count Helper",
        removedRedemptionCountHelper: "Removed Redemption Count Helper",
        activeRedemptionCountHelper: "Active Redemption Count Helper",
        promotionSnapshotAnchorHelper: "Promotion Snapshot Anchor Helper",
        snapshotComplete: "Snapshot Complete",
        snapshotCompleteHelper: "Snapshot Complete Helper",
        discountAmountApplied: "Discount Amount Applied",
        appliedDiscountContribution: "Applied Discount Contribution",
        missingRequiredLinks: "Missing Required Links",
        promotionMissingWhileDraftEditable: "Promotion Missing While Draft Editable",
        promotionOrgMismatch: "Promotion Org Mismatch",
        promotionNotActive: "Promotion Not Active",
        promotionNameSnapshotMissing: "Promotion Name Snapshot Missing",
        discountTypeSnapshotMissing: "Discount Type Snapshot Missing",
        discountTypeSnapshotInvalid: "Discount Type Snapshot Invalid",
        discountAmountSnapshotInvalid: "Discount Amount Snapshot Invalid",
        discountPercentSnapshotInvalid: "Discount Percent Snapshot Invalid",
        discountAmountAppliedInvalid: "Discount Amount Applied Invalid",
        promotionProblem: "Promotion Problem",
        promotionProblemImpactsRedemption: "Promotion Problem Impacts Redemption",
        promotionDriftDetected: "Promotion Drift Detected",
        promotionSnapshotRefreshAllowed: "Promotion Snapshot Refresh Allowed",
        needsSnapshotRefresh: "Needs Snapshot Refresh",
        snapshotRefreshBlocked: "Snapshot Refresh Blocked",
        snapshotRefreshBlockReason: "Snapshot Refresh Block Reason",
        readyToApply: "Ready To Apply",
        applyBlockReason: "Apply Block Reason",
        appliedStateValid: "Applied State Valid",
        removedStateInvalid: "Removed State Invalid",
        applicationRequestedInvalid: "Application Requested Invalid",
        hasOrderItemImpactingException: "Has Order Item Impacting Exception",
        hasStructureProblem: "Has Structure Problem",
        structureProblem: "Structure Problem",
        hasDependencyProblem: "Has Dependency Problem",
        dependencyProblem: "Dependency Problem",
        hasSnapshotProblem: "Has Snapshot Problem",
        snapshotProblem: "Snapshot Problem",
        hasAmountProblem: "Has Amount Problem",
        amountProblem: "Amount Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        createdAt: "Created At",
        modifiedAt: "Modified At",
        appliedAt: "Applied At",
        removedAt: "Removed At",
      },
      orderExternals: {
        order: "Order",
        clientExternal: "Client External",
        orgIntegration: "Organization Integration",
        globalProviderAccount: "Global Provider Account",
        externalActions: "External Actions",
        syncStatus: "Sync Status",
        writebackStatus: "Writeback Status",
        currentExternalStatus: "Current External Status",
        lastProviderActivityAt: "Last Provider Activity At",
        lastSyncedAt: "Last Synced At",
        syncError: "Sync Error",
        writebackAt: "Writeback At",
        writebackError: "Writeback Error",
        notes: "Notes",
        externalOrderId: "External Order ID",
        externalPaymentId: "External Payment ID",
        externalInvoiceId: "External Invoice ID",
        externalPaymentStatusSnapshot: "External Payment Status Snapshot",
        externalInvoiceStatusSnapshot: "External Invoice Status Snapshot",
        externalInvoiceUrlSnapshot: "External Invoice URL Snapshot",
        externalInvoiceSentAtSnapshot: "External Invoice Sent At Snapshot",
        externalInvoicePaidAtSnapshot: "External Invoice Paid At Snapshot",
        customerIdSnapshot: "Customer ID Snapshot",
        cardIdSnapshot: "Card ID Snapshot",
        amountSnapshotCents: "Amount Snapshot Cents",
        rawPayloadSnapshot: "Raw Payload Snapshot",
        organization: "Organization",
        organizationProvider: "Organization Provider",
        organizationProviderAccount: "Organization Provider Account",
        globalProvider: "Global Provider",
        orderOrganization: "Order Organization",
        clientProfile: "Client Profile",
        client: "Client",
        orderStatus: "Order Status",
        billingState: "Billing State",
        paymentCollectionMethod: "Payment Collection Method",
        orderTotal: "Order Total",
        orderAmountPaid: "Order Amount Paid",
        externalActionCount: "External Action Count",
        webhookActionCount: "Webhook Action Count",
        lastActionAtToken: "Last Action At Token",
        lastActionTypeToken: "Last Action Type Token",
        lastActionStatusToken: "Last Action Status Token",
        lastWritebackAtToken: "Last Writeback At Token",
        lastWritebackStatusToken: "Last Writeback Status Token",
        lastActionAt: "Last Action At",
        lastActionType: "Last Action Type",
        lastActionStatus: "Last Action Status",
        lastWritebackAt: "Last Writeback At",
        lastWritebackStatus: "Last Writeback Status",
        provider: "Provider",
        missingProviderContext: "Missing Provider Context",
        hasOrgIntegration: "Has Org Integration",
        hasGlobalProviderAccount: "Has Global Provider Account",
        hasExternalIdentity: "Has External Identity",
        usesInvoiceWrapper: "Uses Invoice Wrapper",
        hasProviderActivity: "Has Provider Activity",
        needsProviderReview: "Needs Provider Review",
        collectionPathSummary: "Collection Path Summary",
        orgIntegrationOrderOrgMismatch: "Org Integration Order Org Mismatch",
        orgIntegrationProviderAccountMismatch: "Org Integration Provider Account Mismatch",
        globalProviderAccountProviderMismatch: "Global Provider Account Provider Mismatch",
        missingRequiredLinks: "Missing Required Links",
        missingExternalId: "Missing External ID",
        invoiceWrapperOnNonInvoicePath: "Invoice Wrapper On Non-Invoice Path",
        paidChargePathMissingPaymentId: "Paid Charge Path Missing Payment ID",
        invoicePathMissingInvoiceId: "Invoice Path Missing Invoice ID",
        failedMissingSyncError: "Failed Missing Sync Error",
        syncedMissingLastSyncedAt: "Synced Missing Last Synced At",
        writebackFailedMissingError: "Writeback Failed Missing Error",
        hasStructureProblem: "Has Structure Problem",
        structureProblem: "Structure Problem",
        hasSyncProblem: "Has Sync Problem",
        syncProblem: "Sync Problem",
        hasPolicyProblem: "Has Policy Problem",
        policyProblem: "Policy Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      refunds: {
        // Primary
        refund: "Refund",
        // Core
        status: "Status",
        refundReason: "Refund Reason",
        requestedAt: "Requested At",
        approvedAt: "Approved At",
        completedAt: "Completed At",
        voidedAt: "Voided At",
        notes: "Notes",
        requestApproval: "Request Approval",
        // Links
        order: "Order",
        // Backlinks
        refundItems: "Refund Items",
        refundExternal: "Refund External",
        // Lookups
        organization: "Organization",
        clientProfile: "Client Profile",
        client: "Client",
        orderStatus: "Order Status",
        orderTotal: "Order Total",
        orderAmountPaid: "Order Amount Paid",
        // Rollups
        refundItemCount: "Refund Item Count",
        refundAmount: "Refund Amount",
        creditsRevoked: "Credits Revoked",
        completedRefundItemCount: "Completed Refund Item Count",
        refundItemExceptionCount: "Refund Item Exception Count",
        // Helpers
        isDraftRefund: "Is Draft Refund",
        isApprovedRefund: "Is Approved Refund",
        isCompletedRefund: "Is Completed Refund",
        isTerminalRefund: "Is Terminal Refund",
        hasRefundItems: "Has Refund Items",
        hasRefundItemExceptions: "Has Refund Item Exceptions",
        refundExceedsOrderTotal: "Refund Exceeds Order Total",
        refundExceedsAmountPaid: "Refund Exceeds Amount Paid",
        // Readiness / Block Reason Helpers
        readyToApprove: "Ready To Approve",
        approveBlockReason: "Approve Block Reason",
        approvedStateValid: "Approved State Valid",
        // Checks
        missingRequiredLinks: "Missing Required Links",
        refundReasonMissing: "Refund Reason Missing",
        refundAmountInvalid: "Refund Amount Invalid",
        orderNotPaid: "Order Not Paid",
        completedWithoutApproved: "Completed Without Approved",
        requestApprovalInvalid: "Request Approval Invalid",
        // Exception System
        hasSetupProblem: "Has Setup Problem",
        setupProblem: "Setup Problem",
        hasAmountProblem: "Has Amount Problem",
        amountProblem: "Amount Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasChildProblem: "Has Child Problem",
        childProblem: "Child Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        // Audit
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      refundItems: {
        // Primary
        refundItem: "Refund Item",
        // Core
        refundAmount: "Refund Amount",
        creditsRevoked: "Credits Revoked",
        notes: "Notes",
        // Links
        refund: "Refund",
        orderItem: "Order Item",
        creditLedgerEntries: "Credit Ledger Entries",
        // Lookups
        refundStatus: "Refund Status",
        organization: "Organization",
        clientProfile: "Client Profile",
        orderFromRefund: "Order (from Refund)",
        orderItemStatus: "Order Item Status",
        orderItemOrganization: "Order Item Organization",
        orderItemLineContribution: "Order Item Line Contribution",
        orderItemCreditsGrantedTotal: "Order Item Credits Granted Total",
        orderItemOfferingNameSnapshot: "Order Item Offering Name Snapshot",
        orderItemHasProblem: "Order Item Has Problem",
        orderItemHasException: "Order Item Has Exception",
        // Rollups
        refundDebitCount: "Refund Debit Count",
        refundDebitTotal: "Refund Debit Total",
        // Helpers
        completedRefundCountHelper: "Completed Refund Count Helper",
        completedRefundAmountContribution: "Completed Refund Amount Contribution",
        hasRefundDebit: "Has Refund Debit",
        expectedRefundDebitCredits: "Expected Refund Debit Credits",
        // Checks
        missingRequiredLinks: "Missing Required Links",
        refundAmountInvalid: "Refund Amount Invalid",
        refundAmountExceedsLineContribution: "Refund Amount Exceeds Line Contribution",
        creditsRevokedInvalid: "Credits Revoked Invalid",
        creditsRevokedExceedsGranted: "Credits Revoked Exceeds Granted",
        orderItemNotActiveOrRefunded: "Order Item Not Active Or Refunded",
        orderItemOrgMismatch: "Order Item Org Mismatch",
        missingRefundDebit: "Missing Refund Debit",
        duplicateRefundDebit: "Duplicate Refund Debit",
        refundDebitAmountMismatch: "Refund Debit Amount Mismatch",
        // Propagation Helpers
        hasRefundImpactingException: "Has Refund Impacting Exception",
        refundDebitEligible: "Refund Debit Eligible",
        // Exception System
        hasSetupProblem: "Has Setup Problem",
        setupProblem: "Setup Problem",
        hasOrgProblem: "Has Org Problem",
        orgProblem: "Org Problem",
        hasAmountProblem: "Has Amount Problem",
        amountProblem: "Amount Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        // Audit
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      refundExternals: {
        // Primary
        refundExternal: "Refund External",
        // Core
        syncStatus: "Sync Status",
        writebackStatus: "Writeback Status",
        currentExternalStatus: "Current External Status",
        externalRefundId: "External Refund ID",
        lastProviderActivityAt: "Last Provider Activity At",
        lastSyncedAt: "Last Synced At",
        syncError: "Sync Error",
        writebackAt: "Writeback At",
        writebackError: "Writeback Error",
        notes: "Notes",
        // Links
        refund: "Refund",
        orgIntegration: "Organization Integration",
        // Backlinks
        externalActions: "External Actions",
        // Lookups from Org Integration
        organization: "Organization",
        provider: "Provider",
        providerAccount: "Provider Account",
        // Lookups from Refund
        refundOrganization: "Refund Organization",
        refundStatus: "Refund Status",
        orderFromRefund: "Order (from Refund)",
        clientProfileFromRefund: "Client Profile (from Refund)",
        clientFromRefund: "Client (from Refund)",
        refundAmount: "Refund Amount",
        creditsRevoked: "Credits Revoked",
        // Rollups
        externalActionCount: "External Action Count",
        // Helpers
        hasExternalRefundId: "Has External Refund ID",
        hasProviderActivity: "Has Provider Activity",
        needsProviderReview: "Needs Provider Review",
        isSynced: "Is Synced",
        refundReadyForProvider: "Refund Ready For Provider",
        // Checks
        missingRequiredLinks: "Missing Required Links",
        canonicalOrgMismatch: "Canonical Org Mismatch",
        missingExternalRefundId: "Missing External Refund ID",
        failedMissingSyncError: "Failed Missing Sync Error",
        syncedMissingLastSyncedAt: "Synced Missing Last Synced At",
        writebackFailedMissingError: "Writeback Failed Missing Error",
        refundNotApproved: "Refund Not Approved",
        // Exception System
        hasSetupProblem: "Has Setup Problem",
        setupProblem: "Setup Problem",
        hasSyncProblem: "Has Sync Problem",
        syncProblem: "Sync Problem",
        hasWritebackProblem: "Has Writeback Problem",
        writebackProblem: "Writeback Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        // Audit
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      providerAccounts: {
        provider: "Provider",
        providerAccountName: "Provider Account Name",
        providerAccountId: "Provider Account ID",
        status: "Status",
        notes: "Notes",
        apiBaseUrl: "API Base URL",
        apiCredentialAlias: "API Credential Alias",
        accessTokenAlias: "Access Token Alias",
        accessToken: "Access Token",
        webhookSigningSecretAlias: "Webhook Signing Secret Alias",
        webhookCredentialId: "Webhook Credential ID",
        orgIntegrations: "Organization Integrations",
        externalActions: "External Actions",
        clientExternals: "Client Externals",
        orgIntegrationCount: "Organization Integration Count",
        activeOrgIntegrationCount: "Active Organization Integration Count",
        clientExternalCount: "Client External Count",
        cardExternalCount: "Card External Count",
        externalActionCount: "External Action Count",
        externalActionWebhookCount: "External Action Webhook Count",
        operationalStatus: "Operational Status",
        enabled: "Enabled",
      },
      appConfig: {
        configKey: "Config Key",
        apiBaseUrl: "API Base URL",
        syncSecretAlias: "Sync Secret Alias",
        testRequested: "Test Requested",
        lastTestAt: "Last Test At",
        lastTestStatus: "Last Test Status",
        lastTestError: "Last Test Error",
        hasApiBaseUrl: "Has API Base URL",
        hasSyncSecretAlias: "Has Sync Secret Alias",
        readyToTest: "Ready To Test",
        missingApiBaseUrl: "Missing API Base URL",
        missingSyncSecretAlias: "Missing Sync Secret Alias",
        testRequestedBlocked: "Test Requested Blocked",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      clientExternals: {
        externalCustomerId: "External Customer ID",
        status: "Status",
        notes: "Notes",
        client: "Client",
        providerAccount: "Provider Account",
        provider: "Provider",
        externalActions: "External Actions",
        cardExternals: "Card Externals",
        nameSnapshot: "Name Snapshot",
        phoneSnapshot: "Phone Snapshot",
        emailSnapshot: "Email Snapshot",
        matchPhoneNormalized: "Match Phone Normalized",
        syncStatus: "Sync Status",
        syncError: "Sync Error",
        lastSyncedAt: "Last Synced At",
        lastSuccessfulCallAt: "Last Successful Call At",
        lastErrorAt: "Last Error At",
        latestPhoneNormalized: "Latest Phone Normalized",
        latestPhoneNormalizedLegacy: "Latest phone normalized",
      },
      cardExternals: {
        cardExternal: "Card External",
        externalCardId: "External Card ID",
        status: "Status",
        notes: "Notes",
        clientExternal: "Client External",
        client: "Client",
        providerAccount: "Provider Account",
        provider: "Provider",
        externalActions: "External Actions",
        brand: "Brand",
        last4: "Last 4",
        expMonth: "Exp Month",
        expYear: "Exp Year",
        cardholderName: "Cardholder Name",
        cardSummary: "Card Summary",
        isActive: "Is Active",
        isUsableForCharge: "Is Usable for Charge",
        hasExternalCardId: "Has External Card ID",
        clientExternalPresent: "Client External Present",
        cardFingerprint: "Card Fingerprint",
        missingRequiredLinks: "Missing Required Links",
        missingExternalCardId: "Missing External Card ID",
        inactiveCardUsed: "Inactive Card Used",
        hasSetupProblem: "Has Setup Problem",
        setupProblem: "Setup Problem",
        hasCardProblem: "Has Card Problem",
        cardProblem: "Card Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      externalActions: {
        externalEntityType: "External Entity Type",
        actionType: "Action Type",
        direction: "Direction",
        triggerSource: "Trigger Source",
        occurredAt: "Occurred At",
        status: "Status",
        attemptNumber: "Attempt Number",
        retryable: "Retryable",
        retryClassification: "Retry Classification",
        notes: "Notes",
        orgIntegration: "Organization Integration",
        providerAccount: "Provider Account",
        clientExternal: "Client External",
        cardExternal: "Card External",
        orderExternal: "Order External",
        refundExternal: "Refund External",
        organization: "Organization",
        orgIntegrationProviderAccount: "Organization Integration Provider Account",
        provider: "Provider",
        client: "Client",
        clientExternalProviderAccount: "Client External Provider Account",
        cardExternalProviderAccount: "Card External Provider Account",
        orderExternalProviderAccount: "Order External Provider Account",
        refundExternalProviderAccount: "Refund External Provider Account",
        providerEventType: "Provider Event Type",
        providerReferenceId: "Provider Reference ID",
        providerEventId: "Provider Event ID",
        httpStatusCode: "HTTP Status Code",
        errorSummary: "Error Summary",
        requestPayload: "Request Payload",
        responsePayload: "Response Payload",
        rawProviderPayload: "Raw Provider Payload",
        writebackStatus: "Writeback Status",
        writebackSucceededAt: "Writeback Succeeded At",
        writebackError: "Writeback Error",
        writebackRetryCount: "Writeback Retry Count",
        writebackLastAttemptAt: "Writeback Last Attempt At",
        lastActionAtToken: "Last Action At Token",
        lastActionTypeToken: "Last Action Type Token",
        lastActionStatusToken: "Last Action Status Token",
        lastWritebackAtToken: "Last Writeback At Token",
        lastWritebackStatusToken: "Last Writeback Status Token",
        hasOrgContext: "Has Org Context",
        hasProviderAccountContext: "Has Provider Account Context",
        hasContext: "Has Context",
        linkedExternalCount: "Linked External Count",
        hasLinkedExternal: "Has Linked External",
        webhookActionCountHelper: "Webhook Action Count Helper",
        missingContext: "Missing Context",
        contextConflictError: "Context Conflict Error",
        missingExternalLink: "Missing External Link",
        multipleExternalLinks: "Multiple External Links",
        clientExternalProviderAccountMismatch: "Client External Provider Account Mismatch",
        cardExternalProviderAccountMismatch: "Card External Provider Account Mismatch",
        orderExternalProviderAccountMismatch: "Order External Provider Account Mismatch",
        refundExternalProviderAccountMismatch: "Refund External Provider Account Mismatch",
        failedMissingError: "Failed Missing Error",
        succeededMissingTimestamp: "Succeeded Missing Timestamp",
        writebackSucceededMissingTimestamp: "Writeback Succeeded Missing Timestamp",
        writebackFailedMissingError: "Writeback Failed Missing Error",
        writebackAttemptedMissingLastAttemptAt: "Writeback Attempted Missing Last Attempt At",
        hasContextProblem: "Has Context Problem",
        contextProblem: "Context Problem",
        hasLinkProblem: "Has Link Problem",
        linkProblem: "Link Problem",
        hasResultProblem: "Has Result Problem",
        resultProblem: "Result Problem",
        hasWritebackProblem: "Has Writeback Problem",
        writebackProblem: "Writeback Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      creditAccounts: {
        // Core
        status: "Status",
        notes: "Notes",
        // Links
        clientProfile: "Client Profile",
        // Lookups
        organization: "Organization",
        client: "Client",
        // Backlinks
        creditLedgerEntries: "Credit Ledger Entries",
        lessons: "Lessons",
        creditReservations: "Credit Reservations",
        // Rollups
        balanceCredits: "Balance Credits",
        creditLedgerEntryCount: "Credit Ledger Entry Count",
        purchaseCreditCount: "Purchase Credit Count",
        purchaseCreditTotal: "Purchase Credit Total",
        lessonDebitCount: "Lesson Debit Count",
        lessonDebitTotal: "Lesson Debit Total",
        refundDebitCount: "Refund Debit Count",
        refundDebitTotal: "Refund Debit Total",
        ledgerEntryExceptionCount: "Ledger Entry Exception Count",
        reservedCredits: "Reserved Credits",
        creditReservationCount: "Credit Reservation Count",
        clientProfileCreditAccountCount: "Client Profile Credit Account Count",
        // Base Helpers
        isActive: "Is Active",
        isPaused: "Is Paused",
        isClosed: "Is Closed",
        hasLedgerEntries: "Has Ledger Entries",
        hasReservations: "Has Reservations",
        hasActiveReservations: "Has Active Reservations",
        hasLedgerExceptions: "Has Ledger Exceptions",
        // Derived Helpers
        availableCredits: "Available Credits",
        lowAvailableCreditFlag: "Low Available Credit Flag",
        multipleCreditAccountsForClientProfile: "Multiple Credit Accounts for Client Profile",
        // Structure Checks
        missingRequiredLinks: "Missing Required Links",
        // Balance Checks
        negativeBalance: "Negative Balance",
        negativeAvailableCredits: "Negative Available Credits",
        reservedCreditsExceedBalance: "Reserved Credits Exceed Balance",
        // Duplicate Checks
        multipleCreditAccounts: "Multiple Credit Accounts",
        // Lifecycle Checks
        closedWithActiveReservations: "Closed With Active Reservations",
        closedWithPositiveBalance: "Closed With Positive Balance",
        pausedWithActiveReservations: "Paused With Active Reservations",
        // Exception System
        hasSetupProblem: "Has Setup Problem",
        setupProblem: "Setup Problem",
        hasBalanceProblem: "Has Balance Problem",
        balanceProblem: "Balance Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        // Audit
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      creditReservations: {
        // Core
        status: "Status",
        reservedCredits: "Reserved Credits",
        reservedAt: "Reserved At",
        resolvedAt: "Resolved At",
        resolutionReason: "Resolution Reason",
        notes: "Notes",
        // Links
        creditAccount: "Credit Account",
        lesson: "Lesson",
        creditLedgerEntries: "Credit Ledger Entries",
        // Lookups
        organization: "Organization",
        clientProfile: "Client Profile",
        client: "Client",
        creditAccountStatus: "Credit Account Status",
        lessonStatus: "Lesson Status",
        lessonOrganization: "Lesson Organization",
        lessonStartAt: "Lesson Start At",
        lessonFutureStartAt: "Lesson Future Start At",
        lessonCancellationReason: "Lesson Cancellation Reason",
        // Rollups
        lockDebitCount: "Lock Debit Count",
        lockDebitTotal: "Lock Debit Total",
        // Helpers
        isActiveReservation: "Is Active Reservation",
        isTerminalReservation: "Is Terminal Reservation",
        activeReservedCredits: "Active Reserved Credits",
        reservationIsActive: "Reservation Is Active",
        hasLockDebit: "Has Lock Debit",
        lockDebitMatchesReservedCredits: "Lock Debit Matches Reserved Credits",
        hoursUntilLessonStart: "Hours Until Lesson Start",
        // Checks
        missingRequiredLinks: "Missing Required Links",
        reservedCreditsInvalid: "Reserved Credits Invalid",
        reservedAtMissing: "Reserved At Missing",
        creditAccountOrgMismatch: "Credit Account Org Mismatch",
        activeReservationOnClosedAccount: "Active Reservation On Closed Account",
        activeReservationOnPausedAccount: "Active Reservation On Paused Account",
        activeReservationLessonNotScheduled: "Active Reservation Lesson Not Scheduled",
        activeReservationLessonNotFuture: "Active Reservation Lesson Not Future",
        terminalWithoutResolutionReason: "Terminal Without Resolution Reason",
        terminalWithoutResolvedAt: "Terminal Without Resolved At",
        consumedWithoutLessonCompleted: "Consumed Without Lesson Completed",
        lockedWithoutLockDebit: "Locked Without Lock Debit",
        duplicateLockDebit: "Duplicate Lock Debit",
        lockDebitAmountMismatch: "Lock Debit Amount Mismatch",
        lockDebitWithoutLockedStatus: "Lock Debit Without Locked Status",
        // Exception System
        hasSetupProblem: "Has Setup Problem",
        setupProblem: "Setup Problem",
        hasOrgProblem: "Has Org Problem",
        orgProblem: "Org Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        // Audit
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      creditLedgerEntries: {
        // Core
        deltaCredits: "Delta Credits",
        entryType: "Entry Type",
        createdVia: "Created Via",
        occurredAt: "Occurred At",
        notes: "Notes",
        reversalReason: "Reversal Reason",
        // Links
        creditAccount: "Credit Account",
        orderItem: "Order Item",
        lesson: "Lesson",
        refundItem: "Refund Item",
        creditReservation: "Credit Reservation",
        reversesCreditLedgerEntry: "Reverses Credit Ledger Entry",
        reversedByCreditLedgerEntry: "Reversed By Credit Ledger Entry",
        // Lookups from Credit Account
        organization: "Organization",
        clientProfile: "Client Profile",
        client: "Client",
        // Lookups from Order Item
        orderItemCreditsGrantedTotal: "Order Item Credits Granted Total",
        // Lookups from Lesson
        lessonCreditsCost: "Lesson Credits Cost",
        lessonStatus: "Lesson Status",
        // Lookups from Refund Item
        refundItemCreditsRevoked: "Refund Item Credits Revoked",
        // Lookups from Credit Reservation
        reservationReservedCredits: "Reservation Reserved Credits",
        lessonStatusFromReservation: "Lesson Status (from Reservation)",
        // Lookups from Reverses Credit Ledger Entry
        reversedEntryType: "Reversed Entry Type",
        reversedDeltaCredits: "Reversed Delta Credits",
        reversedCreditAccount: "Reversed Credit Account",
        // Entry Type Helpers
        isPurchaseCredit: "Is Purchase Credit",
        isLessonDebit: "Is Lesson Debit",
        isRefundDebit: "Is Refund Debit",
        isCreditForfeit: "Is Credit Forfeit",
        isReservationLockDebit: "Is Reservation Lock Debit",
        isAdjustment: "Is Adjustment",
        isReversalEntry: "Is Reversal Entry",
        // Scoped Count / Amount Helpers
        purchaseCreditCountHelper: "Purchase Credit Count Helper",
        purchaseCreditDeltaOnly: "Purchase Credit Delta Only",
        creditForfeitCountHelper: "Credit Forfeit Count Helper",
        creditForfeitDeltaOnly: "Credit Forfeit Delta Only",
        lessonDebitCountHelper: "Lesson Debit Count Helper",
        lessonDebitDeltaOnly: "Lesson Debit Delta Only",
        refundDebitCountHelper: "Refund Debit Count Helper",
        refundDebitDeltaOnly: "Refund Debit Delta Only",
        reservationLockDebitCountHelper: "Reservation Lock Debit Count Helper",
        reservationLockDebitDeltaOnly: "Reservation Lock Debit Delta Only",
        // Source Shape Helpers
        hasSourceLink: "Has Source Link",
        sourceTypeCount: "Source Type Count",
        // Reversal Helpers
        reversalEntryTypeValid: "Reversal Entry Type Valid",
        reversalAccountMatches: "Reversal Account Matches",
        reversalDeltaMatchesOpposite: "Reversal Delta Matches Opposite",
        // Source Keys
        purchaseCreditSourceKey: "Purchase Credit Source Key",
        lessonDebitSourceKey: "Lesson Debit Source Key",
        refundDebitSourceKey: "Refund Debit Source Key",
        creditForfeitureSourceKey: "Credit Forfeiture Source Key",
        reservationLockDebitSourceKey: "Reservation Lock Debit Source Key",
        reversalSourceKey: "Reversal Source Key",
        // Structure Checks
        missingRequiredLinks: "Missing Required Links",
        occurredAtMissing: "Occurred At Missing",
        // Source Checks
        multipleSourceLinksPresent: "Multiple Source Links Present",
        missingSourceLinkForNonAdjustment: "Missing Source Link For Non-Adjustment",
        sourceLinkPresentForPlainAdjustment: "Source Link Present For Plain Adjustment",
        reversalWithSourceLinkPresent: "Reversal With Source Link Present",
        sourceInvalid: "Source Invalid",
        // Amount Checks
        deltaCreditsInvalid: "Delta Credits Invalid",
        purchaseCreditSignInvalid: "Purchase Credit Sign Invalid",
        debitSignInvalid: "Debit Sign Invalid",
        purchaseCreditAmountMismatch: "Purchase Credit Amount Mismatch",
        lessonDebitAmountMismatch: "Lesson Debit Amount Mismatch",
        refundDebitAmountMismatch: "Refund Debit Amount Mismatch",
        reservationLockDebitAmountMismatch: "Reservation Lock Debit Amount Mismatch",
        creditForfeitAmountMismatch: "Credit Forfeit Amount Mismatch",
        // Reversal Checks
        reversalEntryMissingTarget: "Reversal Entry Missing Target",
        manualReversalMissingNotes: "Manual Reversal Missing Notes",
        reversalReasonMissing: "Reversal Reason Missing",
        reversalEntryTypeInvalid: "Reversal Entry Type Invalid",
        reversalAccountMismatch: "Reversal Account Mismatch",
        reversalAmountMismatch: "Reversal Amount Mismatch",
        // Exception System
        hasStructureProblem: "Has Structure Problem",
        structureProblem: "Structure Problem",
        hasSourceProblem: "Has Source Problem",
        sourceProblem: "Source Problem",
        hasAmountProblem: "Has Amount Problem",
        amountProblem: "Amount Problem",
        hasLifecycleProblem: "Has Lifecycle Problem",
        lifecycleProblem: "Lifecycle Problem",
        hasException: "Has Exception",
        exceptionReason: "Exception Reason",
        // Audit
        createdAt: "Created At",
        modifiedAt: "Modified At",
      },
      clients: {
        firstName: "First Name",
        lastName: "Last Name",
        clientName: "Client Name",
        latestPhoneNormalized: "Latest Phone Normalized",
        latestPhoneNormalizedLegacy: "Latest phone normalized",
      },
    },
  },
  core: {
    tables: {
      leadIntakes: "Lead Intakes",
      leadAttributions: "Lead Attributions",
      campaigns: "Campaigns",
    },
    fields: {
      leadIntakes: {
        firstName: "First",
        lastName: "Last",
        phone: "Phone",
        zip: "Zip",
        createdAt: "Created At",
        lessonSetting: "Lesson Setting",
        ageGroup: "Age Group",
        startTimeline: "Start Timeline",
      },
      leadAttributions: {
        leadIntake: "Lead Intake",
        lead: "Lead",
        landingUrl: "Landing URL",
        campaign: "Campaign",
        capturedAt: "Captured At",
      },
      campaigns: {
        campaignCode: "Campaign Code",
      },
    },
  },
} as const;
